apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5678
          env:
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_HOST
              value: "${db_host}"
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_DATABASE
              value: "${db_name}"
            - name: DB_POSTGRESDB_USER
              value: "${db_user}"
            - name: DB_POSTGRESDB_PASSWORD
              value: "${db_password}"
            - name: DB_POSTGRESDB_SSL_ENABLED
              value: "true"
            - name: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
              value: "false"
            - name: N8N_PATH
              value: "/n8n/"
            - name: N8N_EDITOR_BASE_URL
              value: "/n8n/"
            - name: N8N_PORT
              value: "5678"
            - name: N8N_USER_MANAGEMENT_DISABLED
              value: "true"
            - name: N8N_SECURE_COOKIE
              value: "false"
